[project]
name = "iching-stacks-app"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.hexagram-registry]
path = "contracts/hexagram-registry.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
